name: Update YouTube Live M3U

on:
  schedule:
    - cron: "0 */3 * * *"   # हर 3 घंटे पर run होगा
  workflow_dispatch:        # मैन्युअली चलाने का option

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install yt-dlp
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp

    - name: Save cookies
      run: printf '%s' "$YOUTUBE_COOKIES" > youtube_cookies.txt
      env:
        YT_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}

    - name: Run script
      run: python update.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git pull --rebase
        git add news.m3u
        git commit -m "Auto-update news.m3u $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
