name: Update YouTube Live M3U

on:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours (UTC)
  workflow_dispatch:       # allow manual run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      # NEW STEP: write the cookies secret to a file (do NOT echo the value)
      - name: Write YouTube cookies file
        env:
          YT_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
        run: |
          printf '%s' "$YT_COOKIES" > youtube_cookies.txt
          # Check file exists (do NOT print contents)
          ls -lh youtube_cookies.txt

      - name: Generate playlist
        run: |
          python update.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add -A
            git commit -m "Auto-update news.m3u $(date -u +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit"
          fi
